server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'secretkey string'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 21600 #21600


spring:
  servlet:
    multipart:
      location: C:/ItStudy/img
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/educare?serverTimezone=Asia/Seoul
    username: root
    password: '0000'

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1014494943001-ism1d8ml2ehc4g4i33qpn97na88nm4cr.apps.googleusercontent.com
            client-secret: Egaycbq2lYbbGqnxxAqp08H8
            scope:
            - email
            - profile

logging:
  level:
    io.educare: INFO         
#          facebook:
#            client-id: 1338148343232032
#            client-secret: e3786e7bdb4743d020cf2b98e9155942
#            scope:
#            - email
#            - public_profile
#            
#          naver:
#            client-id: YfcQarLGkNJtnpaWWtjU
#            client-secret: RWz9MeHYJr
#            scope:
#            - name
#            - email
#            # - profile_image
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            # 네이버는 provider가 아니므로 명시해줘야 함, 단 주소 고정값아니고 마음대로 변경 가능
#            redirect-uri: http://localhost:8000/login/oauth2/code/naver
#            
#        provider:
#          naver:
#            # 네이버 정보 요청하는 url
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴함
#            user-name-attribute: response 
